#!/usr/bin/env bash
#transfer file from client to server

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh="$4"

export SSH_OPTIONS="-o StrictHostKeyChecking=no"

scp -i "$path_to_ssh" "$SSH_OPTIONS" "$path_to_file" "$username"@"$ip":~
