#!/usr/bin/env bash
#configure Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx start
sudo sed -i 's/#listen 80;/listen 80;/' /etc/nginx/sites-available/default
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
