#!/usr/bin/env bash
#configure load balancer

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

sudo apt-get install -y haproxy=2.8.\*

sudo chmod 666 /etc/haproxy/haproxy.cfg
sudo cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend backend-servers

backend backend-servers
    balance roundrobin
    server web-01 web-01.100.24.74.170:80 check
    server web-02 web-02.18.234.80.72:80 check
EOF

sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

sudo service haproxy start
sudo service haproxy enable
