#!usr/bin/env bash
#creating backup

current_date=$(date +%d-%m-%Y)

backup_file="backup.sql"
archive_file="$current_date.tar.gz"

mysqldump -u root -p "$1" --all-databases > "$backup_file"

tar -czvf "$archive_file" "$backup_file"
