#!/usr/bin/env bash
#this script does something

pid=$(pgrep 7-highlander)

if [ -z "$pid" ]; then
    	echo "The 7-highlander process is not running."
else
    	kill -s SIGTERM "$pid"
       	while [ -e /proc/"$pid" ]; do sleep 0.1; done
	echo "The 7-highlander process has been stopped."
fi
