#!/usr/bin/env bash
#this script does something

function sigterm_handler {
    	echo "I am invincible!!!"
    	exit 0
}

trap sigterm_handler SIGTERM

while true; do
    	echo "To infinity and beyond indefinitely"
    	sleep 2
done
