#!/usr/bin/env bash
#this script uses while loop to print Best school 10 times but do smt different on the 9th

count=1

while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count = 9 ]
    then
	    echo "Hi"
    fi

    count=$((count+1))
done
