#!/usr/bin/env bash
#this script uses while loop to print Best school 10 times but do smt different on the 9th

count=1

while [ $count -le 10 ]
do
    if [ $count = 4 ]
    then
	    echo "bad luck"
    elif [ $count = 8 ]
    then
	    echo "good luck"
    else
	    echo "Best School"
    fi

    count=$((count+1))
done
