#!/usr/bin/env bash
#this script uses while loop to print Best school 10 times but do smt different on the 9th

count=1

while [ $count -le 20 ]
do
	echo "$count"
    	if [ $count = 4 ]
    	then
	    	echo "bad luck from China"
    	elif [ $count = 9 ]
    	then
	    	echo "bad luck from Japan"
	elif [ $count = 17 ]
	then
	    	echo "bad luck from Italy"
    	fi

    	count=$((count+1))
done
