#!/usr/bin/env bash
#run nginx as nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx stop
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
sudo service nginx start
